# Copyright 2024-2025 New Vector Ltd
# Copyright 2025-2026 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

apiVersion: v2
name: matrix-stack
version: 26.1.5-dev
kubeVersion: '>= 1.22.0-0'
description: A Helm chart for deploying a Matrix Stack from Element
type: application
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAiWSURBVHgB1ZtLbFRVGMe/c2dGaui0g1GMxr4SNVFpLRgXaokdEAUxAVcaTLRuTOpGmliFFWWFOhhgQxM3UhOI7jCxPmLLTALRhERbqY+FJkzbBSoqU1qgMJ17/P53eie3c+/M3Me5hf4SOsO5z/Od73yvc0ZQyNSlD7TGKNItCtQpBbUIIVq5OSEltVrPE4Ky/JGTUmYFyZ+kRuN50sfnk3uzFCKCQqA+faBbK0R2kiZ2lHfUB1l+zYzU8kNzyb0ZUowyASTSAwmdVr8ldbGbSCYoHLJ87/15rZBRpRmBBbBMHS9D5HiaHLuhLRwJKohAAmhIH+SO08DyddxGFhoxu/mdY+QTXwJIsGEryOjHJKmbbg2yeW0h6UcbNPIIRr2gx8Zuoc6D1pgeHWsYfX83ecSTBjSkU4dY5T0/ZDkRGg1cTvbvd32+2xPj6YMfky57aEUgjs1ufvt1V2e6OSk+khrnMx+lFQQHVuOXN/Wvr3VeTRtgjPwK6zzgAKwzPsrvXoOqAmhIf7hv5ai9E7KnYTR1qNoZFadA0cfLw6SQrkQTNd/eaHyfmp+hmfx1mpj7m8JGkN53efO7h52POWD4ebg6hQHOK/eso8GHttrap+Yv0+lLU3T8z1/ozKVpCokcxwnrneIExymg69G06ujuzaYNju3NdQ2GcL5c/xL9/OQb9MJdD1AIJGII3BywCSA++kGPpMAZnI0cq3stIIwT7TsMTWmM1pFSOHBzCpSWTAGoPkY/DAF01N9FxztepBbupBswNbb/+ClN8qdCchEt2pZL9uXMhoj16G09W/ex+9hKIfDXjat04sLPNPJvlo5f+IWN30Wa1wu0dtVqqtOitvMbo6uM6TB88XeaWaitPS6pI7lw/fonIxmzoaQBRcMXHcNXWmZgA/a0PemoHdCEp85+wkKYJ0Us0YKSBsRefW4ny+NlCgnM7/b4WsMNQurWUYUrxEg31zXSg6vvWHIdNKFOi9DIf1lSxBItKGkABwznVc79BL94b9Nj1LWmiTay/7eCUd117iSdc4gB3nsgyR7jMVv79rHP2F0qc5O52c39a/DFEEB9OtUtdEqTAqDGRx/eZut0OV9c/IN2TZx0PDbMLnHjmqXXn85Ns1H8jFTBWW1ybkt/xnCDXLHtIQXs5Xk8wb68VudBY2xVxWMQTLnhwz3LhRIELSJ3Gp/4w5nT0xQAqPvwhpcMAbhlcPrHisfQ+aPTP9jat995P6lCSrEDn2LR+p8nn0Dlhze8bBi5SkB9J2b/NuZ+jjs3MfuX4QarAeOHyBCfJrh+3XcfkSo4PG6LFgqxThKS/HKiY6dj59HRQR5FjKQfP45rzrHQrGqP5+DflKLgKKZHuqNCFDql99KgAVS+vX6trR3WHVY+6IsO//OHbd7DjZr3RaC0p+2J4rlsVA+c/468wFO/Myql1umnNgzVd5rziPL2/H5KSfTmdI8WjhXO0LTxfOQNJh08EGd4qnlxlewJWjUuIraQD44+tM3WhpHv/e0rZaFrteivqa7R1tbs0FYNXqdsge57Dn27HFwS5jzUXiUYzXJhonYAElXcqFskHJifxctX7nnE1gaDN6U2czM6/9TZIY4ONxn/P2p5htNoT3KVySOtUfLBxjXNtrbjnOmFgRE2O0SMXYn7bG0zee9Tz7P5R15f7vYQ1qoe/WrAAJZXjlA38FNf9L405lCpgfU1gYAQGyAy7HBwkSrYxemz7R0WbYNXtMWdGa5pud0+96auFUffjApf4JAVsTuEoLq0hWc4ZYsoqvogCw3IUUByhaK7Qr5vDV2LVR118TuAdlmfARBq+6koc/iT0zgYmPRy0dS1GVdtqkHCNcixh1Pk2fvrV+QHKeVkVGgyy5mR64sgbYSc2xdH9r3z35cMoJMg2tkmBMWI+njknTqPd/FrgIWQ44gDxskjeKhT3O1UwcW08ItZVcKcL1d7gMjTa/xvBX2PRrRChtNhUgECF4yG1U3CGMIQ1ipqwnusi99tdNqsH1YrrEwultWCkI/o44buN5zieqBUUw90qulV0hgT+HRrYlMLTEN0PmDOkeW6YNtiHCA/J0UgLS0HAqm2INJ73wZyi2F/uDYYPOESGfw1BKAXhLIs5rRDSor5i0JpJdzU/HFfVIOCzHkrvPI9hM+S+Y+Ppi6RokURMwgqB/lC729f29orLZuZ/t1vVakKhvrjS8n6sSSOcHq4jxSAF8dLl9sCrADBIO7lgonVY5zj+iDWAc0MD3sHws0tZGkTlWVp7FCioC+gOKpEC6D2qO93OLhBdA6qjNWgnNqRdcOSvQJLIiBeHRpQpQWgeTE3qGQAodammpurRNMcTE2GOPoc/R2Ze+ad0jJ52fK4Wi0AtYRQDoSC/P90OLtFbDtKlyyPzw99Mx977dnrLBVlS+ToEJbFsQT+eOO9Nc/Heaj8nrjgK7urgey7umlPxtrimATET6XSYWyFbTdqBbU3ScAodp0dIsWULL8Vx4JIRCxgl2XgNLkcrAa1sy9/ngMZuMRKc31w6gdSi4DhSzoeqXTJ6tHUbpZO1T12KoBWwDWWts+xEbRWmFSg69R3ZUu/+21yJvUjBw9zyvgWrWCkru+f2/LuQKXjNQsB8ZHUMT7rNVqJSBqafaa/p9opriohnC2OYe8trSQk/cSdr/nOrqrCxq5rliatFIoj72rAXJfFoUpcP3T9Q4SbBSK9WmpvxdO6wNyW/gGdqI9CcJHBETlYe2uY6+oq8kGYO0p9ISiT59jFz4+mAv1sDvuKBYl9N08QGHW5v5KPd3UHCgi0YaEQ2y0MV7l8P5zkis6RaPTK4VxyINB0DCwAk+Jmq0h3uBqhruOlO1II1H+b6maN6MH2u6DCMNYudfm5LsVJbGwkxYQiACuGZhRincXNWJFHObRupao/nxdZIfVJKSLj+Rs3MvPbwv35/P/R2+j03RrulQAAAABJRU5ErkJggg==
keywords:
  - ESS
  - Element
  - Matrix
  - Synapse
  - ElementWeb
  - MAS
  - MatrixAuthenticationService
  - ElementAdmin
  - MatrixRTC
home: https://element.io/server-suite
sources:
  - https://github.com/element-hq/ess-helm
  - https://github.com/element-hq/synapse
  - https://github.com/element-hq/element-web
  - https://github.com/element-hq/matrix-authentication-service
  - https://github.com/element-hq/element-admin
  - https://github.com/element-hq/lk-jwt-service
dependencies: []
maintainers:
  - name: Element - Server Products Team
